apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: terra10-rs-r2
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - terra10-r2
  template:
    metadata:
      labels:
        app: terra10-r2
    spec:
      containers:
      - name: terra10
        image: lgorissen/terra10:r2
