apiVersion: v1
kind: Pod
metadata:
  name: terra10-volumes
  labels:
    planet: terra10-sub2
    transporter: local-11
  annotations:
    build: 20181029-01
    builder: LGO
spec:
  containers:
  - image: lgorissen/terra10
    name: terra10
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "name"
            fieldRef:
              fieldPath: metadata.name
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "limits.cpu"
            resourceFieldRef:
              containerName: terra10
              resource: limits.cpu
              divisor: 1m
          - path: "requests.cpu"
            resourceFieldRef:
              containerName: terra10
              resource: requests.cpu
              divisor: 1m
          - path: "limits.memory"
            resourceFieldRef:
              containerName: terra10
              resource: limits.memory
              divisor: 1
          - path: "requests.memory"
            resourceFieldRef:
              containerName: terra10
              resource: requests.memory
              divisor: 1

