apiVersion: v1
kind: Pod
metadata:
  name: apiserver-via-sidecar
spec:
  containers:
  - name: main
    image: lgorissen/terra10-curl
    command: ["sleep", "9999999"]
  - name: sidecar
    image: lgorissen/terra10-kubectl-proxy
