apiVersion: v1
kind: Service
metadata:
  name: terra10-hs
spec:
  clusterIP: None
  selector:
    app: terra10
  ports:
  - name: http-transporter
    port: 8090
    targetPort: 8090
  - name: http-monitor
    port: 8092
    targetPort: 8092
