apiVersion: v1
kind: Pod
metadata:
  name: terra10-simple-secret
spec:
  containers:
  - image: lgorissen/terra10
    name: terra10
    volumeMounts:
    - name: mysecretvolume
      mountPath: "/etc/terra10"
      readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: mysecretvolume
    secret:
      secretName: terra10-from-file
