apiVersion: v1
kind: Pod
metadata:
  name: terra10-transporter-hostpath
spec:
  containers:
  - image: lgorissen/terra10-transporter
    name: terra10-transporter
    volumeMounts:
    - name: transportlog-hostpath
      mountPath: /tmp
    ports:
    - containerPort: 8092
      protocol: TCP
  - image: lgorissen/terra10-monitor
    name: terra10-monitor
    volumeMounts:
    - name: transportlog-hostpath
      mountPath: /var/log
      readOnly: true
    ports:
    - containerPort: 8090
      protocol: TCP
  volumes:
  - name: transportlog-hostpath
    hostPath:
      path: /tmp/terra10-transporter

