apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: gpu-monitor-ds
spec:
  selector:
    matchLabels:
      app: gpu-monitor
  template:
    metadata:
      labels:
        app: gpu-monitor
    spec:
      nodeSelector:
        gpu: high
      containers:
      - name: main
        image: lgorissen/gpu-monitor
