apiVersion: v1
kind: Pod
metadata:
  name: terra10-record-2874
  labels:
    microservice: record
    rel: 18.1.3
spec:
  containers:
  - image: lgorissen/terra10
    name: terra10
    ports:
    - containerPort: 8080
      protocol: TCP
