apiVersion: v1
kind: PersistentVolume
metadata:
  name: terra10-transporter-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/terra10-transporter
