apiVersion: batch/v1
kind: Job
metadata:
  name: terra10-batch-job
spec:
  template:
    metadata:
      labels:
        app: terra10-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: lgorissen/terra10-job
