apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: terra10-dpl
spec:
  replicas: 3
  minReadySeconds: 20
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: terra10
      labels:
        app: terra10
    spec:
      containers:
      - name: terra10
        image: lgorissen/terra10:r1
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
